name: Test Pipeline with Docker Compose and Cypress

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Setup Docker
        uses: docker/setup-qemu-action@v2

      - name: Start MongoDB Database using Docker Compose
        run: docker-compose up -d

      - name: Wait for MongoDB to Initialize
        run: |
          sleep 10
          docker ps

      - name: Import Data into MongoDB
        run: node cypress/mongodb/import.js

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          MONGO_URI: ${{secrets.MONGO_URI}}
          MONGO_COLLECTION: ${{secrets.MONGO_COLLECTION}}
          MONGO_DB: ${{secrets.MONGO_DB}}

      - name: Insert information to report
        run: |
          sh scripts/trendreports.sh

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: cypress/reports/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
        with:
          keepFiles: true

      - name: Stop Docker Compose
        run: docker-compose down
